/*
 * This source file was generated by the Gradle 'init' task
 */
package org.testingapp;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public int show(){
        return 0;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting() + new App().show());
    }
}
